### ISSUE TITLE
Publish to AUR repositories

### ISSUE THREAD

**Issue by aslafy-z** [turbot/powerpipe#248]
**Is your feature request related to a problem? Please describe.**
I'd love to use AUR to install powerpipe as I do for steampipe

**Describe the solution you'd like**
Create a powerpipe-bin package on AUR

**Describe alternatives you've considered**
Make the package myself, however, I'm not sure I would keep up with the updates. It would be better if it could be done as part of the release pipeline.  

**Additional context**

https://aur.archlinux.org/packages/steampipe-bin

**Comment by pskrbasu** [comment]
@aslafy-z Meanwhile if you want to make the package yourself for now, you can go ahead.
