### ISSUE TITLE
mod.sp is not created

### ISSUE THREAD

**Issue by electriquo** [turbot/powerpipe#257]
**Describe the bug**

I saw the deprecation message

> Deprecation warning: Steampipe mods and dashboards have been moved to Powerpipe. This command will be removed in a future version. Migration guide - https://powerpipe.io/blog/migrating-from-steampipe

Changing `steampipe mod install` to `powerpipe mod install` raised the following error when trying to start Steampipe

```shell
Error: This command requires a mod definition file (mod.sp) - could not find in the current directory tree.

You can either clone a mod repository or install a mod using steampipe mod install and run this command from the cloned/installed mod directory.
Please refer to: https://steampipe.io/docs/mods/overview
```

Indeed, `$STEAMPIPE_MOD_LOCATION/mod.sp` was missing when using `powerpipe` but not when using `steampipe`

**Powerpipe version (`powerpipe -v`)**
Example: 0.1.1

**To reproduce**

1. Delete `$STEAMPIPE_MOD_LOCATION/mod.sp`
2. Install Steampipe mods using powerpipe
3. Start Steampipe

**Expected behavior**

Either `$STEAMPIPE_MOD_LOCATION/mod.sp` should be created by powerpipe, or it should not make steampipe fail. And ability to migrate to powerpipe easily.

**Comment by pskrbasu** [comment]
Hey @electriquo, when you say `Start Steampipe` what command are you running? Are you running `steampipe service start --dashboard` or any other?

**Comment by pskrbasu** [comment]
@electriquo When you run `powerpipe mod install`, it creates a `mod.pp` file instead of a .sp file. Steampipe does not understand .pp files.

If you want to run dashboards, you can run `powerpipe server` after running `powerpipe mod install` from your $STEAMPIPE_MOD_LOCATION.

See: https://powerpipe.io/docs/reference/cli/server
