### ISSUE TITLE
Text resource support for args

### ISSUE THREAD

**Issue by gabrielsoltz** [turbot/powerpipe#300]
Hey, hello 👋 

We are trying to build dynamic [text](https://powerpipe.io/docs/powerpipe-hcl/text) resources based on other resources, like input resources, but it seems it's not supported... 

This could be really useful for relying on text resources to create dynamic links to other dashboards and set GET parameters. 

For example: 

```
input "team" {
  # title = "Select a Team"
  type  = "select"
  width = 4
  option "Team1" {
    label = "Team 1"
  }

text {
    value = <<-EOM
        ### Dashboards: [Dashboard 1](${var.host}/local.dashboard.main?input.team=$1
      EOM
     args = {
        team = self.input.team.value
      }
  }
```

**Comment by kaidaguerre** [comment]
what errors are you seeing  when you try to use this approach

**Comment by kaidaguerre** [comment]
@gabrielsoltz what errors are you seeing when you try to use this approach
