### ISSUE TITLE
.ppvars file parsing bug when defining variables that follows HCL formatting

### ISSUE THREAD

**Issue by danlsgiga** [turbot/powerpipe#302]
**Describe the bug**
Defining a `.ppvars` config file with more than 1 spaces between the variable name and the `=` sign render the following error.

```
[ Error   ] failed to load variables from 'aws_tags.auto.ppvars'
Argument or block definition required: An argument or block definition is required here. To set an argument, use the equals sign "=" to introduce the argument value.
(aws_tags.auto.ppvars:3,1)
```

**Powerpipe version (`powerpipe -v`)**
Example: v0.1.3

**To reproduce**
- Create an `aws_tags.auto.ppvars` file in the workspace
- Set a variable like this: `aws_tags.common_dimensions    = ["account_id", "region"]`
- Rendering fails
- Set a variable like this: `aws_tags.common_dimensions = ["account_id", "region"]`
- Rendering succeeds

**Expected behavior**
Since `.ppvars` configs are basically HCL, this should never happen since HCL accepts and, in fact, encourages this type of alignment via `fmt`

**Comment by pskrbasu** [comment]
@danlsgiga Thanks for raising this. We'll look into getting this fixed.
