### ISSUE TITLE
Powerpipe dashboard displaying incomplete results

### ISSUE THREAD

**Issue by aditivarade** [turbot/powerpipe#305]
Hi,

I utilized your Steampipe Docker image tailored for AWS Cloud to generate several reports. Below is a screenshot showcasing the outcomes derived from the HTML report.
<img width="908" alt="image" src="https://github.com/turbot/powerpipe/assets/71124990/83ede56d-0944-4aed-a535-0689a4b0f339">
Command: docker run --rm -e AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} -e AWS_REGION=${AWS_REGION} \
                          -e AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} -e AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN} \
                          --name steampipe-compliance --mount type=bind,source="${pwd}",target=/output \
                          steampipe-aws-compliance check all --export /output/AWS_Report.html

I've delved into the functionalities of [steampipe-mod-aws-compliance](https://github.com/turbot/steampipe-mod-aws-compliance) and went through the process of manually installing Steampipe and Powerpipe. 

When executing the "powerpipe benchmark run aws_compliance.benchmark.all_controls" command, it indicates 158 errors detected. However, I'm unable to view any additional results or the successfully passed benchmarks (OK) on the dashboard, unlike when I conduct the analysis using the docker image.
<img width="944" alt="image" src="https://github.com/turbot/powerpipe/assets/71124990/4e59aa56-70fd-4802-90f2-23559b5bd34f">
<img width="946" alt="image" src="https://github.com/turbot/powerpipe/assets/71124990/185a656d-05c1-42b0-9ef7-89f5ed68600e">
Furthermore, I haven't observed any details regarding the resources upon which the errors have been detected.
<img width="949" alt="image" src="https://github.com/turbot/powerpipe/assets/71124990/4eaad34b-5bc5-4122-b4e0-42fb4a42f759">

**Steps I have followed to set up steampipe with powerpipe**

1. I followed the documentation provided for [steampipe-mod-aws-compliance](https://github.com/turbot/steampipe-mod-aws-compliance  )
    Below are the versions installed on my Ubuntu VM
    Powerpipe version (`powerpipe -v`)
    **Powerpipe v0.1.3**
    Steampipe version (`steampipe -v`)
 **Steampipe v0.22.1**
2.  For AWS credentails I tried both the approaches
     a) Exported environment variables on my VM 
     b) Created the aws credentials file
3.  Ran the steampipe and powerpipe commands
     steampipe service start
     powerpipe server
4.  Ran the powerpipe benchmark command
     powerpipe benchmark run aws_compliance.benchmark.all_controls

For your informartion I have used the same AWS user and its credentials in both the cases(steampipe docker image and steampipe with powerpipe) 

**Expected behavior**
The PowerPipe dashboard should showcase comprehensive outcomes, including thorough details regarding the resources it has scanned through.

**Comment by e-gineer** [comment]
The error in the dashboard indicates that Steampipe cannot find / resolve your AWS credentials. Are you sure it's picking up the steampipe configuration properly?

**Comment by aditivarade** [comment]
Hi @e-gineer,

I tried the following steps for setting up the credentials 

1. Exported AWS environment variables on my VM
2. Created the aws credentials file
3. In the aws.spc file I mentioned the profile specified in the aws credentials file
    connection "aws_account_a" {
    plugin = "aws"
    profile = "account_extensure"
    }
4. And in the aws credentials file I have mentioned the following details
    [account_extensure]
    aws_access_key_id = ${aws_access_key_id}
    aws_secret_access_key = ${aws_secret_access_key}
    aws_session_token = ${aws_session_token}
5. Created a user called steampipe and ran the following commands using the created steampipe user
     **steampipe service start**
     **powerpipe benchmark run aws_compliance.benchmark.all_controls**

Please let me know if I am missing anything else.

**Comment by e-gineer** [comment]
How is docker involved in your setup? You mention that at the start, but not in the latest info.

Are you able to run basic queries against the steampipe instance you have created? (i.e. before using powerpipe with it)

**Comment by aditivarade** [comment]
Earlier, I utilized Docker to explore Steampipe, but currently I have install both Steampipe and Powerpipe directly on my local virtual machine (VM). 
Answering to you question, I'm currently unable to execute queries. To troubleshoot, I verified the functionality of my AWS credentials by employing the command "aws sts get-caller-identity" and configured them for Steampipe as per the steps I previously outlined. However, I am not sure why Steampipe fails to recognize these credentials.
Do let me know if I have missed anything as per the steps I had listed earlier.

**Comment by aditivarade** [comment]
Hi @e-gineer, 

Any update?

**Comment by pskrbasu** [comment]
Hi @aditivarade,

> I'm currently unable to execute queries

What is the error you're seeing when executing queries?

**Comment by aditivarade** [comment]
Hi @pskrbasu,

I tried to execute a simple query("**select name from aws_iam_role**"). Below is the error I get inspite of configuring the credentials correctly.

**Error: aws_account_a: operation error IAM: ListRoles, exceeded maximum number of attempts, 9, failed to sign request: failed to retrieve credentials: failed to refresh cached credentials, no EC2 IMDS role found, operation error ec2imds: GetMetadata, exceeded maximum number of attempts, 3, request send failed, Get "http://169.254.169.254/latest/meta-data/iam/security-credentials/": net/http: timeout awaiting response headers (SQLSTATE HV000)**

**Comment by kaidaguerre** [comment]
@aditivarade it is worth ensuring there are no stray processes left over from previous failed runs. You can list staempipe processes with `ps aux | grep steampipe`, and kil any stray processes with `pkill -f steampipe`

Please could you give that a go then retry.

**Comment by aditivarade** [comment]
@kaidaguerre tried listing the processes and killing them, but no luck.

**Comment by aditivarade** [comment]
@kaidaguerre - The issue is resolved. Appreciate the responses.

**Comment by IgnatG** [comment]
@aditivarade  can I check how this was resolved? I'm having similar issues
