### ISSUE TITLE
on the web UI of powerpipe, the selected search_path disappear when i click a dashboard

### ISSUE THREAD

**Issue by jzhuuuu** [turbot/powerpipe#325]
so i can reproduce this issue with the following steps:
go to the home page
specify the search_path
then go to "AWS EKS Cluster Detail"
then 'the search_path' is gone.
could happen to other dashboard/report, but i just tested this one.

**Comment by philricelf** [comment]
we are also experiencing this issue  and it is across any 'detail' dashboard . Changing to any detail dashboard page, clears the search path that is set and you then need to re-select  the search path / connection again.

This is obviously not good usability wise

**Comment by philricelf** [comment]
adding a comment as this is still an issue

**Comment by MichaelBurgess** [comment]
@philricelf we have a fix for this.

I'm not sure around testing / release timelines - @pskrbasu can best advise when we'd likely be able to release this.
