### ISSUE TITLE
Add an option to hide dependent mod benchmarks in the dashboard

### ISSUE THREAD

**Issue by sbldevnet** [turbot/powerpipe#353]
**Is your feature request related to a problem? Please describe.**
Using a custom mod with other mods as dependencies will cause all benchmarks included in the dependent mods to be displayed in the Web UI running powerpipe as a server.

Depending on the mods included in the dependencies, the number of benchmarks can be elevated (> 100), making the usage more complicated for users who only need to use the custom mod benchmarks.

**Describe the solution you'd like**
I want to be able to choose whether to display the benchmarks of the dependent mods or only the ones declared in the custom mod.

Some ideas on how this could be configured:
- As a flag in the `powerpipe server` command, e.g `powerpipe server --no-include-dependencies`
- As an environment variable, e.g `POWERPIPE_SERVER_INCLUDE_DEPENDENCIES=true`
- Inside the `dashboard` hcl resource, e.g:
```
dashboard "my_example_dashboard" {
  title = "My example Dashboard"

  include_dependencies = false
}
```

**Describe alternatives you've considered**
A workaround would be to include all the needed code in the custom mod and avoid using dependencies. But this will increase the complexity and maintenance of the custom mod.

**Additional context**

**Comment by pskrbasu** [comment]
@sbldevnet You can use the `Group by:` option in the powerpipe dashboard server webpage to group by mods.

![Screenshot 2024-05-16 at 2 56 54 PM](https://github.com/turbot/powerpipe/assets/45908484/c63c95a5-0365-4f0f-b53d-f4acab6bbc78)

**Comment by sbldevnet** [comment]
Yes @pskrbasu, but I would like to be able to hide them by default.
