### ISSUE TITLE
POWERPIPE_PORT is not honored

### ISSUE THREAD

**Issue by electriquo** [turbot/powerpipe#362]
**Describe the bug**

[POWERPIPE_PORT](https://powerpipe.io/docs/reference/env-vars/powerpipe_port) environment variable is not honored by `powerpipe server` and it forces to pass `--port "$POWERPIPE_PORT"` option, otherwise the default port (9033) is used.

Below you can see that although POWERPIPE_PORT environment variable is used, powerpipe server does not honor it and listens on the default port (9033).

```shell
$ env | grep POWERPIPE_PORT
POWERPIPE_PORT=9194

$ powerpipe server
[ Wait    ] Starting WorkspaceEvents Server
[ Message ] WorkspaceEvents loaded
[ Message ] Initialization complete
[ Ready   ] Dashboard server started on 9033 and listening on local
[ Message ] Visit http://localhost:9033
[ Message ] Press Ctrl+C to exit
```

**Powerpipe version (`powerpipe -v`)**

```shell
$ powerpipe -v
Powerpipe v0.3.1
```

**To reproduce**

1. Use [POWERPIPE_PORT](https://powerpipe.io/docs/reference/env-vars/powerpipe_port)
2. Execute `powerpipe server`
3. Try to access powerpipe with the port specified in POWERPIPE_PORT

**Expected behavior**

POWERPIPE_PORT environment variable should be honored by `powerpipe server` without specifying `--port` option.
 
**Additional context**

- https://powerpipe.io/docs/reference/env-vars/powerpipe_port

**Comment by pskrbasu** [comment]
Thanks for raising this @electriquo. We will get this fixed. 👍
