### ISSUE TITLE
Support new pipe-fittings `UniqueNameGenerator.GetUniqueName` signature 

### ISSUE THREAD

**Issue by MichaelBurgess** [turbot/powerpipe#416]
We now need to pass the column index to the function as well as the name.

**Comment by pskrbasu** [comment]
https://github.com/turbot/powerpipe/commit/faf3b6c3e93bfb2ac1057579a77782ebbcba6deb#diff-dac75ad59caddeb3e90231a073127f572fc67da1851120d8f3b33cbef72dae9d
