### ISSUE TITLE
STDOUT of `powerpipe benchmark run` doesn't follow `--output` option when a new version is available

### ISSUE THREAD

**Issue by k-kawa** [turbot/powerpipe#452]
**Describe the bug**
When a new version of powerpipe is available, `powerpipe benchmark run --output json` command prints a notification to its stdout  so that the output results in an invalid JSON string.

**Powerpipe version (`powerpipe -v`)**
v0.4.0

**To reproduce**
Run the command with its not-latest binary.

**Expected behavior**
The format of the command follows `--output` option even if its new version is available. The notification message should be printed to its stderr not stdout.

**Additional context**

**Comment by pskrbasu** [comment]
Thanks @k-kawa for finding this. We will fix it asap.
