### ISSUE TITLE
Powerpipe uses only the last value when using `--tag` multiple times

### ISSUE THREAD

**Issue by binaek** [turbot/powerpipe#491]
**Describe the bug**
When using the `--tag` flag with `powerpipe benchmark run` or `powerpipe control run`, only the last value is considered.

**Powerpipe version (`powerpipe -v`)**
v0.4.0

**To reproduce**
`powerpipe benchmark run benchmark.infra_compliance --dry-run --database sqlite://:memory: --tag service=AWS/S3 --tag service=GCP/Storage`

**Expected behavior**
All controls for GCP as well as AWS should run. Only the GCP controls are running.

**Comment by kaidaguerre** [comment]
Fixed by https://github.com/turbot/pipe-fittings/commit/2eeb06dc50e82fdbf569af95e8bd3bd05d5326d6
