### ISSUE TITLE
Couldn't connect with "Client Secret Credentials"

### ISSUE THREAD

**Issue by antonin78** [turbot/powerpipe#494]
**Describe the bug**
When I edit the file microsoft365.spc, with the following content:

```
connection "microsoft365_via_sp_secret" {
    plugin        = "microsoft365"
    tenant_id     = "2782adbXXXXXXXXXXXXXXXXXd7af333622"
    client_id     = "5fa4379c-3XXXXXXXXXXXXXXXXXXX5ef32a83"
    client_secret = "rRI8Q~EpzCeXXXXXXXXXXXXXXXSYI0xb8K"
  }
```
I start the powerpipe server but when I run a CIS check, i've got the following error:

`azuread: {"Code":"","Message":"AzureCLICredential: ERROR: Please run 'az login' to setup account.\r\n"} (SQLSTATE HV000)`

**Powerpipe version (`powerpipe -v`)**
Example: v0.4.3

**To reproduce**
Follow the issue details

**Expected behavior**
The result on the tenant of the differents CIS benchmark details.

**Comment by ParthaI** [comment]
Resolved in https://github.com/turbot/steampipe-mod-microsoft365-compliance/issues/69#issuecomment-2358758675
