### ISSUE TITLE
Error: during development, dashboard assets must be present when running powerpipe dashboard

### ISSUE THREAD

**Issue by TheInverseKey** [turbot/powerpipe#524]
Powerpipe version (powerpipe -v)
v1.0.0

To reproduce

    Follow the instructions from https://github.com/turbot/powerpipe/blob/develop/README.md
        instead of the installer scripts, I installed steampipe and powerpipe 
       ` the powerpipe -v works` and `powerpipe query run "select title from aws_account"`
    Follow the instructions from https://powerpipe.io/docs#visualize-cloud-infrastructure
        When running powerpipe server, it prints `Error: during development, dashboard assets must be present when running powerpipe dashboard` and exits.

**Comment by TheInverseKey** [comment]
@pskrbasu Is there an ETA on a fix for this?

**Comment by pskrbasu** [comment]
@TheInverseKey I will try and get the error message fixed next week. Thanks!

**Comment by pskrbasu** [comment]
Error message updated in v1.0.1
