### ISSUE TITLE
Columns of type `DATE` have `00:00:00Z` in values

### ISSUE THREAD

**Issue by cbruno10** [turbot/powerpipe#565]
For values that are just dates (YYYY-MM-DD), should we add `00:00:00Z`?![Image](https://github.com/user-attachments/assets/6bbf9143-549c-460b-9473-2548e279ad5f)

**Comment by MichaelBurgess** [comment]
Fixed in [v1.1.0-alpha.202411201016](https://github.com/turbot/powerpipe/releases/tag/v1.1.0-alpha.202411201016)
