### ISSUE TITLE
Missing input, but it's defined

### ISSUE THREAD

**Issue by ibaraki-douji** [turbot/powerpipe#623]
**Describe the bug**
I'm currently facing an error where my input is not found but it's defined in the dashboard.

```
Error: failed to load workspace: Bad Request: Failed to resolve dependencies after 3 passes. Unresolved blocks:
   dashboard.only_aws -> self.input.project.label
     MISSING: input.project
```

**Powerpipe version (`powerpipe -v`)**
Example: v1.0.1

**To reproduce**
You also need AWS Insights to make it work.
```hcl
locals {
    vpc_id = "vpc-xxx"
}

dashboard "only_aws" {

    title = "Only AWS"

    input "project" {
        title = "Select a project"
        query = query.vpc_subnets
        width = 4
    }

    graph {
        title = "VPC"

        node {
            base = aws_insights.node.vpc_vpc
            args = {
                vpc_vpc_ids = [local.vpc_id]
            }
        }

        node {
            base = aws_insights.node.vpc_subnet
            args = {
                vpc_subnet_ids = with.vpc_project_subnets_from_subnet.rows[*].value
            }
        }
    }

    text {
        value = self.input.project.label
    }

    with "vpc_project_subnets_from_subnet" {
        query = query.vpc_project_subnets_from_subnet
        args = [self.input.project.label]
    }
}

query "vpc_subnets" {
  sql = <<-EOQ
    select distinct on (label)
      substring(substring(title from position('-' in title) + 1) from 1 for char_length(substring(title from position('-' in title) + 1)) - 2) as label,
      subnet_id as value
    from
      aws_vpc_subnet;
  EOQ
}

query "vpc_project_subnets_from_subnet" {
  sql = <<-EOQ
    select
      title as label,
      subnet_id as value
    from
      aws_vpc_subnet
    where
      title like '%' || $1 || '%';
  EOQ

  param "label" {}
}
```

**Expected behavior**
It should find the input.project

**Additional context**

**Comment by pskrbasu** [comment]
Hey @ibaraki-douji, looking at your dashboard hcl, it seems that the `text` block defined in the dashboard is breaking. The `with` block with the same input(self.input.project.label) defined in args is not causing the problem.
```
text {
        value = self.input.project.label
    }

    with "vpc_project_subnets_from_subnet" {
        query = query.vpc_project_subnets_from_subnet
        args = [self.input.project.label]
    }
```

It might be that the issue could be related to the text block being unable to render its value from the input block. Anyway, the error is not helpful here either. 

This is my initial observation, I will keep on looking into this and keep you updated. Meanwhile you can trying removing the text block for now and see if the issue persists while I keep digging.

Thanks!

**Comment by ibaraki-douji** [comment]
i think ye, it's the text block not allowing self.input as a value, i also think others block like a with can't be put inside the text block value

**Comment by pskrbasu** [comment]
@ibaraki-douji 

An `input` can only be used as an arg or in a `with` block. The `input` resources are evaluated during runtime and not during parse time. So, using it inside resources that evaluate its values during parse time causes it to fail. It's not designed to work that way.

input doc: https://powerpipe.io/docs/powerpipe-hcl/input#input

**Comment by ibaraki-douji** [comment]
Oh mb i looked inside the `text` block docs for that i didn't see anything there.
Thx for providing the rights docs, tho a bit sad that we can't put a dynamic element inside a `text` block.
